language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/dinosaure/ocaml-travisci-skeleton/master/.travis-docgen.sh
script: bash -ex .travis-opam.sh
sudo: true
env:
  global:
    - PACKAGE="checkseum"
  matrix:
  - OCAML_VERSION=4.07 TEST=true
  - OCAML_VERSION=4.07 TEST=false DEPOPTS="mirage-xen-posix"
  - OCAML_VERSION=4.07 TEST=false DEPOPTS="ocaml-freestanding"
  - OCAML_VERSION=4.08 TEST=true
  - OCAML_VERSION=4.09 TEST=true
