language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/dinosaure/ocaml-travisci-skeleton/master/.travis-docgen.sh
script: bash -ex .travis-opam.sh
sudo: true
env:
  global:
    - PACKAGE="checkseum"
  matrix:
  - OCAML_VERSION=4.03 TEST=true
  - OCAML_VERSION=4.04 TEST=true
  - OCAML_VERSION=4.05 TEST=true
  - OCAML_VERSION=4.05 TEST=false EXTRA_DEPS="mirage-xen"
  - OCAML_VERSION=4.06 TEST=true
  - OCAML_VERSION=4.07 TEST=true
  - OCAML_VERSION=4.07 TEST=false EXTRA_DEPS="mirage-solo5"
